# Generated by Django 4.2.7 on 2023-12-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rent_mon_cost',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
