# Generated by Django 4.2.7 on 2023-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_units_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(default='./media/pic/contact.png', upload_to='pic/'),
        ),
    ]
