# Generated by Django 4.2.7 on 2023-12-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_tenant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prop', to='home.property'),
        ),
    ]
