# Generated by Django 4.2.7 on 2023-12-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_rent_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(default='./pic/contact.png', upload_to='pic/'),
        ),
    ]
